paypal.client.id=BAAL-ET8u6PcKXNW7yGnstiO1xSvglTSwtwxDm57-uEnmnkSpG5GR6AyHR7TjYCW-hF6-tQFQZcK5aLMj8
paypal.client.secret=EK0Obfdgz4hhKo1ZdkSTpkeMs5ZToGgyanqas1jh9H7W1QiOohWuQRadZ9Uhfjj0V6KWS8bZ8sekd52k
paypal.mode=sandbox # or 'live' for production